function [AR_pred,ht_pred,PuL,rnd_ret,VaR,GARCHOutput_add] =  BacktestUniGARCH(GARCHOutput,start,daten,forecastP,archP,garchQ,n)

%  Backtest for univariate GARCH models. Computes several univariate GARCH
% models with time-varying information (information will always be added).
%
% USAGE:
%      [AR_pred,ht_pred,PuL,Sum_AR_pred,rnd_ret] =...
%      BacktestUniGARCH(GARCHOutput,start,daten,forecastP,archP,garchQ)
%
% % INPUTS:
%           start:       starting point for first forecast period; first part of
%                        sample will be used for first model
%           daten:       t x k array of return series
%     GARCHOutput:       Structure from estimation of univariate GARCH
%       forecastP:       # of periods to be forecasted
%           archP:       # of ARCH lags in univariate GARCH
%          garchQ:       # of GARCH lags in univariate GARCh
%
% OUTPUTS:
%         AR_pred:      1 period forecast for conditional mean
%         ht_pred:      1 period forecast of variance
%           resid:      residuals form AR(p)-regression (not forecasted)
%             PuL:      profit & loss for array "daten"
%         rnd_ret:      return series generated by estimated univariate GARCH
%                       models (use for VaR)
% GARCHOutput_add:      structure from estimated GARCH models
%
% Author: Martin Grziska, 05/23/2010


[t,k]=size(daten);

if GARCHOutput{1}.const==1
    const=1;
else
    const=0;
end

%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%%
% Für den Backtest:
% Bestimme GARCH-Modelle über Zeitfenster, wobei bei einem bestimmten
% Zeitpunkt angefangen wird und dann sukzessive Perioden (forecastP) hinzugefügt werden
g=1;
for i=start:forecastP:t
    [GARCHOutput_add{g}] = AR_MarginalModel_add(daten(1:i,:),archP,garchQ,GARCHOutput);
    g=g+1;
end


% Bestimme größte AR-laglänge, um alle Zeitreihen auf die gleiche
% Datenanzahl zu bringen
maxarlag=zeros(k,1);
arlag=zeros(k,1);
ardiff=zeros(k,1);
for i=1:k
    maxarlag(i)=GARCHOutput{i}.arlag;
    arlag(i) = GARCHOutput{i}.arlag;
end
maxarlag = max(maxarlag);
for i=1:k
    if GARCHOutput{i}.arlag<maxarlag
        ardiff(i) = maxarlag-GARCHOutput{i}.arlag;
    else ardiff(i) = 0;
    end
end

% Bestimme über die zweite Hälfte des samples den forecast für die
% univariaten GARCH-Varianzen und Mean, sowie die Residuen, die sich
% ergeben durch daten-AR_pred: daten_t = omega + PHI*daten_t-1
% daten:kompletter datensatz
% Auch hier werden jeweils wie oben die Modelle mit sukzessiv zunhemnden
% % Datensätzen geschätzt
% % der forecast betragt sowohl für mean als auch variance 1 Periode;
% zu maxarlag: Daten werden um k-lags im AR(k) gelagged
g=1;
for i=start:forecastP:t-forecastP
    [AR_pred_all{g},ht_pred_all{g}, resid_all{g}, PuL_all{g}] = ar_univariate_snoop_forecast1P(daten(1:i+forecastP,:),GARCHOutput_add{g},const);
    g=g+1;
end
% for last forecast use remaining returns
[AR_pred_all{g},ht_pred_all{g}, resid_all{g}, PuL_all{g}] = ar_univariate_snoop_forecast1P(daten,GARCHOutput_add{g},const);

% erste forecast
AR_pred = cell(k,1);
ht_pred = cell(k,1);
resid = cell(k,1);
for i=1:k
    AR_pred{i}=AR_pred_all{1}{i}(end-forecastP+1:end);
    ht_pred{i}=ht_pred_all{1}{i}(end-forecastP+1:end);
    resid{i}=resid_all{1}{1}(end-forecastP+1:end);
end
PuL = PuL_all{1}(end-forecastP+1:end);
% setze alle anderen forecasts untereinander, so dass eine Zeitreihe mit
% forecasts entsteht
for j=2:size(AR_pred_all,2)
    for i=1:k
        AR_pred{i} = [AR_pred{i};AR_pred_all{j}{i}(end-forecastP+1:end)];
        ht_pred{i} = [ht_pred{i};ht_pred_all{j}{i}(end-forecastP+1:end)];
        resid{i} = [resid{i};resid_all{j}{i}(end-forecastP+1:end)];
    end
    PuL = [PuL;PuL_all{j}(end-forecastP+1:end)];
end

% korrigiere den letzen forecast, dort werden (eventuell) zuviel Elemente
% verwendet - wenn die Differenz zwischen t und start nicht genau durch
% forecastP teilbar ist, werden bei dem letzten forecast zuviele Variablen
% verwendet; dies überlappt sich dann mit dem vorletzten forecast
c = start:forecastP:t;
wrongnumb = forecastP-(t-c(end));
for i=1:k
    AR_pred{i} = AR_pred{i}(1:end-wrongnumb);
    ht_pred{i} = ht_pred{i}(1:end-wrongnumb);
    resid{i} = resid{i}(1:end-wrongnumb);
end
PuL = PuL(1:end-wrongnumb);

% generate random returns based on previous results
rnd_ret = cell(k,1);
for i=1:k
    h=1;
    for j=1:size(AR_pred{1},1)
        if strcmp(GARCHOutput_add{h}{i}.dist,'GAUSS') == 1
            rnd_ret{i}{j}  = sort(AR_pred{i}(j) + sqrt(ht_pred{i}(j))*normrnd(0,1,n,1));
        elseif strcmp(GARCHOutput_add{h}{i}.dist,'STUDENTST') == 1
            rnd_ret{i}{j}  = sort(AR_pred{i}(j) + sqrt(ht_pred{i}(j))*trnd(GARCHOutput_add{h}{i}.ParamsGARCH(end),n,1));
        elseif strcmp(GARCHOutput_add{h}{i}.dist,'GED') == 1
            rnd_ret{i}{j}  = sort(AR_pred{i}(j) + sqrt(ht_pred{i}(j))*gedrnd(GARCHOutput_add{h}{i}.ParamsGARCH(end),n,1));
        elseif strcmp(GARCHOutput_add{h}{i}.dist,'SKEWT') == 1
            rnd_ret{i}{j}  = sort(AR_pred{i}(j) + sqrt(ht_pred{i}(j))*skewtdis_rnd(GARCHOutput_add{h}{i}.ParamsGARCH(end-1),GARCHOutput_add{h}{i}.ParamsGARCH(end),n));
        end
        g=1:forecastP:size(GARCHOutput_add,2);
        if j==g(h)&&j>1
            h=h+1;
        end
    end
end

VaR_95 = zeros(size(AR_pred{1},1),k);
VaR_05 = zeros(size(AR_pred,1),k);
VaR_99 = zeros(size(AR_pred,1),k);
VaR_01 = zeros(size(AR_pred,1),k);
VaR_90 = zeros(size(AR_pred,1),k);
VaR_10 = zeros(size(AR_pred,1),k);
for i=1:k
    for h=1:size(AR_pred{1},1)
        VaR_95(h,i) = quantile(rnd_ret{i}{h},.05)';
        VaR_05(h,i) = quantile(rnd_ret{i}{h},.95)';
        VaR_99(h,i) = quantile(rnd_ret{i}{h},.01)';
        VaR_01(h,i) = quantile(rnd_ret{i}{h},.99)';
        VaR_90(h,i) = quantile(rnd_ret{i}{h},.010)';
        VaR_10(h,i) = quantile(rnd_ret{i}{h},.90)';
    end
end

VaR_99_all = zeros(size(AR_pred{1},1),1);
VaR_01_all = zeros(size(AR_pred{1},1),1);
VaR_95_all = zeros(size(AR_pred{1},1),1);
VaR_05_all = zeros(size(AR_pred{1},1),1);
VaR_90_all = zeros(size(AR_pred{1},1),1);
VaR_10_all = zeros(size(AR_pred{1},1),1);
for i=1:k
    VaR_99_all = VaR_99_all+1/k*VaR_99(:,i);
    VaR_01_all = VaR_01_all+1/k*VaR_01(:,i);
    VaR_05_all = VaR_05_all+1/k*VaR_05(:,i);
    VaR_95_all = VaR_95_all+1/k*VaR_95(:,i);
    VaR_90_all = VaR_90_all+1/k*VaR_90(:,i);
    VaR_10_all = VaR_10_all+1/k*VaR_10(:,i);
end

VaR=[VaR_99_all VaR_01_all VaR_95_all VaR_05_all VaR_90_all VaR_10_all];

% VaR (95/1)
figure
a=area(VaR_95_all(:,1));
set(a,'FaceColor',[1 1 0])
hold on
b=area(VaR_05_all(:,1));
set(b,'FaceColor',[1 1 0])
hold on
plot(PuL,'.')
title('VaR(95/1)')

% VaR (99/1)
figure
a=area(VaR_99_all(:,1));
set(a,'FaceColor',[1 1 0])
hold on
b=area(VaR_01_all(:,1));
set(b,'FaceColor',[1 1 0])
hold on
plot(PuL,'.')
title('VaR(99/1)')

% VaR (90/1)
figure
a=area(VaR_90_all(:,1));
set(a,'FaceColor',[1 1 0])
hold on
b=area(VaR_10_all(:,1));
set(b,'FaceColor',[1 1 0])
hold on
plot(PuL,'.')
title('VaR(90/1)')

