function [logL, isValid, Rt, likelihoods, Qt] = ...
    dccFilterForRequestedOutputs(requestedOutputs, stdResiduals, ...
    conditionalVariances, qBar, archMatrices, garchMatrices, ...
    asymmetricMatrices, negativeQBar)
%DCCFILTERFORREQUESTEDOUTPUTS Avoid allocating unrequested DCC paths.

    if requestedOutputs <= 1
        [logL, isValid] = dccCorrelationFilter(stdResiduals, ...
            conditionalVariances, qBar, archMatrices, garchMatrices, ...
            asymmetricMatrices, negativeQBar);
        Rt = [];
        likelihoods = [];
        Qt = [];
    elseif requestedOutputs == 2
        [logL, isValid, Rt] = dccCorrelationFilter(stdResiduals, ...
            conditionalVariances, qBar, archMatrices, garchMatrices, ...
            asymmetricMatrices, negativeQBar);
        likelihoods = [];
        Qt = [];
    elseif requestedOutputs == 3
        [logL, isValid, Rt, likelihoods] = dccCorrelationFilter( ...
            stdResiduals, conditionalVariances, qBar, archMatrices, ...
            garchMatrices, asymmetricMatrices, negativeQBar);
        Qt = [];
    else
        [logL, isValid, Rt, likelihoods, Qt] = dccCorrelationFilter( ...
            stdResiduals, conditionalVariances, qBar, archMatrices, ...
            garchMatrices, asymmetricMatrices, negativeQBar);
    end
end
